(in-package :cl-user)

(defpackage :cl-gccjit-ffi
  (:nicknames "gccjit-ffi")
  (:use :cl)
  (:import-from :cffi
                :defctype
                :defcfun
                :defcenum)
  (:export :gcc-jit-context
           :gcc-jit-result
           :gcc-jit-object
           :gcc-jit-location
           :gcc-jit-type
           :gcc-jit-field
           :gcc-jit-struct
           :gcc-jit-function-type
           :gcc-jit-vector-type
           :gcc-jit-function
           :gcc-jit-block
           :gcc-jit-rvalue
           :gcc-jit-lvalue
           :gcc-jit-param
           :gcc-jit-case
           :gcc-jit-extended-asm
           :gcc-jit-context-acquire
           :gcc-jit-context-release
           :gcc-jit-str-option
           :gcc-jit-int-option
           :gcc-jit-bool-option
           :gcc-jit-context-set-str-option
           :gcc-jit-context-set-int-option
           :gcc-jit-context-set-bool-option
           :gcc-jit-context-set-bool-allow-unreachable-blocks
           :gcc-jit-context-set-bool-print-errors-to-stderr
           :gcc-jit-context-set-bool-use-external-driver
           :gcc-jit-context-add-command-line-option
           :gcc-jit-context-add-driver-option
           :gcc-jit-context-compile
           :gcc-jit-output-kind
           :gcc-jit-context-compile-to-file
           :gcc-jit-context-dump-to-file
           :gcc-jit-context-set-logfile
           :gcc-jit-context-get-first-error
           :gcc-jit-context-get-last-error
           :gcc-jit-result-get-code
           :gcc-jit-result-get-global
           :gcc-jit-result-release
           :gcc-jit-object-get-context
           :gcc-jit-object-get-debug-string
           :gcc-jit-context-new-location
           :gcc-jit-location-as-object
           :gcc-jit-type-as-object
           :gcc-jit-types
           :gcc-jit-context-get-type
           :gcc-jit-context-get-int-type
           :gcc-jit-type-get-pointer
           :gcc-jit-type-get-const
           :gcc-jit-type-get-volatile
           :gcc-jit-type-get-restrict
           :gcc-jit-compatible-types
           :gcc-jit-type-get-size
           :gcc-jit-context-new-array-type
           :gcc-jit-context-new-field
           :gcc-jit-context-new-bitfield
           :gcc-jit-field-as-object
           :gcc-jit-context-new-struct-type
           :gcc-jit-context-new-opaque-struct
           :gcc-jit-struct-as-type
           :gcc-jit-struct-set-fields
           :gcc-jit-struct-get-field
           :gcc-jit-struct-get-field-count
           :gcc-jit-context-new-union-type
           :gcc-jit-context-new-funciton-ptr-type
           :gcc-jit-context-new-param
           :gcc-jit-param-as-object
           :gcc-jit-param-as-lvalue
           :gcc-jit-param-as-rvalue
           :gcc-jit-function-kind
           :gcc-jit-tls-model
           :gcc-jit-context-new-function
           :gcc-jit-context-get-builtin-function
           :gcc-jit-function-as-object
           :gcc-jit-function-get-param
           :gcc-jit-function-dump-to-dot
           :gcc-jit-function-new-block
           :gcc-jit-block-as-object
           :gcc-jit-block-get-function
           :gcc-jit-global-kind
           :gcc-jit-context-new-global
           :gcc-jit-context-new-struct-constructor
           :gcc-jit-context-new-union-constructor
           :gcc-jit-context-new-array-constructor
           :gcc-jit-global-set-initializer-rvalue
           :gcc-jit-context-get-target-builtin-funciton
           :gcc-jit-global-set-initializer
           :gcc-jit-global-set-randomly
           :gcc-jit-lvalue-as-object
           :gcc-jit-lvalue-as-rvalue
           :gcc-jit-rvalue-as-object
           :gcc-jit-rvalue-get-type
           :gcc-jit-context-new-rvalue-from-int
           :gcc-jit-context-new-rvalue-from-long
           :gcc-jit-context-zero
           :gcc-jit-context-one
           :gcc-jit-context-new-rvalue-from-double
           :gcc-jit-context-new-rvalue-from-ptr
           :gcc-jit-context-null
           :gcc-jit-context-new-sizeof
           :gcc-jit-context-new-alignof
           :gcc-jit-context-new-string-literal
           :gcc-jit-unary-op
           :gcc-jit-context-new-unary-op
           :gcc-jit-binary-op
           :gcc-jit-context-new-binary-op
           :gcc-jit-comparison
           :gcc-jit-context-new-comparison
           :gcc-jit-context-new-call
           :gcc-jit-context-new-call-through-ptr
           :gcc-jit-context-new-cast
           :gcc-jit-context-new-bitcast
           :gcc-jit-lvalue-set-alignment
           :gcc-jit-lvalue-get-alignment
           :gcc-jit-context-new-array-access
           :gcc-jit-context-convert-vector
           :gcc-jit-context-new-rvalue-vector-perm
           :gcc-jit-context-new-vector-access
           :gcc-jit-lvalue-access-field
           :gcc-jit-rvalue-access-field
           :gcc-jit-rvalue-dereference-field
           :gcc-jit-rvalue-dereference
           :gcc-jit-lvalue-get-address
           :gcc-jit-lvalue-set-tls-model
           :gcc-jit-lvalue-set-link-section
           :gcc-jit-lvalue-set-register-name
           :gcc-jit-function-new-local
           :gcc-jit-function-new-temp
           :gcc-jit-block-add-eval
           :gcc-jit-block-add-assignment
           :gcc-jit-block-add-assignment-op
           :gcc-jit-block-add-comment
           :gcc-jit-block-end-with-conditional
           :gcc-jit-block-end-with-jump
           :gcc-jit-block-end-with-return
           :gcc-jit-block-end-with-void-return
           :gcc-jit-context-new-case
           :gcc-jit-case-as-object
           :gcc-jit-block-end-with-switch
           :gcc-jit-context-new-child-context
           :gcc-jit-context-dump-reproducer-to-file
           :gcc-jit-context-enable-dump
           :gcc-jit-timer
           :gcc-jit-timer-new
           :gcc-jit-timer-release
           :gcc-jit-context-set-timer
           :gcc-jit-context-get-timer
           :gcc-jit-timer-push
           :gcc-jit-timer-pop
           :gcc-jit-timer-print
           :gcc-jit-rvalue-set-bool-require-tail-call
           :gcc-jit-type-get-aligned
           :gcc-jit-type-get-vector
           :gcc-jit-function-get-address
           :gcc-jit-context-new-rvalue-from-vector
           :gcc-jit-version-major
           :gcc-jit-version-minor
           :gcc-jit-version-patchlevel
           :gcc-jit-block-add-extended-asm
           :gcc-jit-block-end-with-extended-asm-goto
           :gcc-jit-extended-asm-as-object
           :gcc-jit-extended-asm-set-volatile-flag
           :gcc-jit-extended-asm-set-inline-flag
           :gcc-jit-extended-asm-add-output-operand
           :gcc-jit-extended-asm-add-input-operand
           :gcc-jit-extended-asm-add-clobber
           :gcc-jit-add-top-level-asm
           :gcc-jit-function-get-return-type
           :gcc-jit-function-get-param-count
           :gcc-jit-type-dyncast-array
           :gcc-jit-type-is-bool
           :gcc-jit-type-dyncast-function-ptr-type
           :gcc-jit-function-type-get-return-type
           :gcc-jit-function-type-get-param-count
           :gcc-jit-function-type-get-param-type
           :gcc-jit-type-is-integral
           :gcc-jit-type-is-pointer
           :gcc-jit-type-dyncast-vector
           :gcc-jit-type-is-struct
           :gcc-jit-vector-type-get-num-units
           :gcc-jit-vector-type-get-element-type
           :gcc-jit-type-unqualified
           :gcc-jit-fn-attribute
           :gcc-jit-funciton-add-attribute
           :gcc-jit-function-add-string-attribute
           :gcc-jit-function-add-integer-array-attribute
           :gcc-jit-variable-attribute
           :gcc-jit-lvalue-add-string-attribute
           :gcc-jit-context-set-output-ident))
