(in-package :cl-user)

(defpackage :cl-gccjit
  (:nicknames :gccjit)
  (:use :cl)
  (:import-from :alexandria :with-gensyms)
  (:export :*debug-logging*
   :*debug-logging-destination*
           :defcfun-debug-logging))

(defpackage :cl-gccjit-ffi
  (:nicknames :gccjit-ffi)
  (:import-from :cffi
   :defctype
                :defcfun
   :defcenum)
  (:import-from :cl-gccjit :defcfun-debug-logging)
  (:export :context
   :result
           :object
   :location
           :type
   :field
           :struct
   :function-type
           :vector-type
   :function
           :block
   :rvalue
           :lvalue
   :param
           :case
   :extended-asm
           :context-acquire
   :context-release
           :str-option
   :int-option
           :bool-option
   :context-set-str-option
           :context-set-int-option
   :context-set-bool-option
           :context-set-bool-allow-unreachable-blocks
   :context-set-bool-print-errors-to-stderr
           :context-set-bool-use-external-driver
   :context-add-command-line-option
           :context-add-driver-option
   :context-compile
           :output-kind
   :context-compile-to-file
           :context-dump-to-file
   :context-set-logfile
           :context-get-first-error
   :context-get-last-error
           :result-get-code
   :result-get-global
           :result-release
   :object-get-context
           :object-get-debug-string
   :context-new-location
           :location-as-object
   :type-as-object
           :types
   :context-get-type
           :context-get-int-type
   :type-get-pointer
           :type-get-const
   :type-get-volatile
           :type-get-restrict
   :compatible-types
           :type-get-size
   :context-new-array-type
           :context-new-field
   :context-new-bitfield
           :field-as-object
   :context-new-struct-type
           :context-new-opaque-struct
   :struct-as-type
           :struct-set-fields
   :struct-get-field
           :struct-get-field-count
   :context-new-union-type
           :context-new-funciton-ptr-type
   :context-new-param
           :param-as-object
   :param-as-lvalue
           :param-as-rvalue
   :function-kind
           :tls-model
   :context-new-function
           :context-get-builtin-function
   :function-as-object
           :function-get-param
   :function-dump-to-dot
           :function-new-block
   :block-as-object
           :block-get-function
   :global-kind
           :context-new-global
   :context-new-struct-constructor
           :context-new-union-constructor
   :context-new-array-constructor
           :global-set-initializer-rvalue
   :context-get-target-builtin-funciton
           :global-set-initializer
   :global-set-randomly
           :lvalue-as-object
   :lvalue-as-rvalue
           :rvalue-as-object
   :rvalue-get-type
           :context-new-rvalue-from-int
   :context-new-rvalue-from-long
           :context-zero
   :context-one
           :context-new-rvalue-from-double
   :context-new-rvalue-from-ptr
           :context-null
   :context-new-sizeof
           :context-new-alignof
   :context-new-string-literal
           :unary-op
   :context-new-unary-op
           :binary-op
   :context-new-binary-op
           :comparison
   :context-new-comparison
           :context-new-call
   :context-new-call-through-ptr
           :context-new-cast
   :context-new-bitcast
           :lvalue-set-alignment
   :lvalue-get-alignment
           :context-new-array-access
   :context-convert-vector
           :context-new-rvalue-vector-perm
   :context-new-vector-access
           :lvalue-access-field
   :rvalue-access-field
           :rvalue-dereference-field
   :rvalue-dereference
           :lvalue-get-address
   :lvalue-set-tls-model
           :lvalue-set-link-section
   :lvalue-set-register-name
           :function-new-local
   :function-new-temp
           :block-add-eval
   :block-add-assignment
           :block-add-assignment-op
   :block-add-comment
           :block-end-with-conditional
   :block-end-with-jump
           :block-end-with-return
   :block-end-with-void-return
           :context-new-case
   :case-as-object
           :block-end-with-switch
   :context-new-child-context
           :context-dump-reproducer-to-file
   :context-enable-dump
           :timer
   :timer-new
           :timer-release
   :context-set-timer
           :context-get-timer
   :timer-push
           :timer-pop
   :timer-print
           :rvalue-set-bool-require-tail-call
   :type-get-aligned
           :type-get-vector
   :function-get-address
           :context-new-rvalue-from-vector
   :version-major
           :version-minor
   :version-patchlevel
           :block-add-extended-asm
   :block-end-with-extended-asm-goto
           :extended-asm-as-object
   :extended-asm-set-volatile-flag
           :extended-asm-set-inline-flag
   :extended-asm-add-output-operand
           :extended-asm-add-input-operand
   :extended-asm-add-clobber
           :add-top-level-asm
   :function-get-return-type
           :function-get-param-count
   :type-dyncast-array
           :type-is-bool
   :type-dyncast-function-ptr-type
           :function-type-get-return-type
   :function-type-get-param-count
           :function-type-get-param-type
   :type-is-integral
           :type-is-pointer
   :type-dyncast-vector
           :type-is-struct
   :vector-type-get-num-units
           :vector-type-get-element-type
   :type-unqualified
           :fn-attribute
   :funciton-add-attribute
           :function-add-string-attribute
   :function-add-integer-array-attribute
           :variable-attribute
   :lvalue-add-string-attribute
           :context-set-output-ident))
