name: CI

on:
  - push
  - pull_request

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}
      LISP: sbcl-bin
      QUICKLISP_DIST: ultralisp

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install libgccjit (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgccjit-14-dev libgccjit0
          version: 1.0

      - name: Install libgccjit (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: libgccjit gcc
          cache: yes

      - name: Extra libgccjit setup (macOS)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew link libgccjit gcc

      - name: Setup
        uses: 40ants/setup-lisp@v4
        with:
          asdf-system: cl-gccjit
          cache: true
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org

      - name: Run tests
        uses: 40ants/run-tests@v2
        with:
          asdf-system: cl-gccjit
